#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

##############################################################
# Update system node path to nvm default node path
##############################################################
update_system_node_path() {
  SYSTEM_NODE_PATH="/usr/local/bin/node"
  NVM_DEFAULT_NODE_PATH="$(nvm which default)"
  ln -Ffsv "$NVM_DEFAULT_NODE_PATH" "$SYSTEM_NODE_PATH" >& /dev/null
}
update_system_node_path
